--- #YAML:1.0
name:               Amazon-SNS
version:            1.0
abstract:           Amazon Simple Notification Service made simpler
author:
    - Alessandro Zummo <a.zummo@towertech.it>
license:            GPLv2
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Accessor::Fast:  0
    LWP::UserAgent:       0
    Net::Amazon::AWSSign:  0
    XML::Simple:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
