---
abstract: 'Amazon Simple Notification Service made simpler'
author:
  - 'Alessandro Zummo <a.zummo@towertech.it>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Amazon-SNS
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor::Fast: 0
  JSON: 0
  LWP::UserAgent: 0
  URI::Escape: 0
  XML::Simple: 0
version: 1.2
